site_name: Machine Learning
site_author: Maria Gabriela Santos
site_url: https://mgabriel4.github.io/machine-learning/
repo_url: https://github.com/mgabriel4/machine-learning
repo_name: github/machine-learning

theme:
  name: material
  palette:
    - scheme: default
      primary: deep_purple
      toggle:
        icon: fontawesome/solid/moon
        name: Switch to dark mode

    - media: "(prefers-color-scheme)"
      primary: deep_purple
      toggle:
        icon: fontawesome/solid/sun
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep_purple
      toggle:
        icon: fontawesome/solid/moon
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      primary: deep_purple
      scheme: slate
      toggle:
        icon: fontawesome/solid/sun
        name: Switch to system preference

  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tooltips
    - navigation.instant
    - navigation.instant.progress
    - navigation.top
    - navigation.path
    - navigation.tracking
    - navigation.expand

  icon:
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables
  - footnotes
  - pymdownx.snippets:
      url_download: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format:
        - name: python
          class: python
          # validator: !!python/name:markdown_exec.validator
          # format: !!python/name:markdown_exec.formatter
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

plugins:
  - search
  - glightbox
  - git-revision-date-localized:
      enable_creation_date: true
  - git-authors
  - git-committers:
      repository: https://mgabriel4.github.io/machine-learning/
      branch: main
  - badges
  - minify:
      minify_html: true
  - markdown-exec
  - render_swagger:
      allow_arbitrary_locations: true
  - termynal:
      prompt_literal_start:
        - "$"
        - ">"

extra_javascript:
  - https://unpkg.com/mathjax/es5/tex-mml-chtml.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://fastly.jsdelivr.net/npm/jquery/dist/jquery.min.js
  - https://fastly.jsdelivr.net/npm/echarts/dist/echarts.min.js

nav:
  - Home: index.md
  - Conceitos Iniciais: ./classes/conceitos/main.md
  - Árvore de decisão: 
    - Conceito: ./classes/arvore-de-decisao/conceito.md
    - Projeto 1: ./classes/arvore-de-decisao/classificacao.md
    - Projeto 2: ./classes/arvore-de-decisao/regressao.md
  - KNN:
    - Conceito: ./classes/knn/conceito.md
    - Projeto: ./classes/knn/main.md
  - K-Means:
    - Conceito: ./classes/k-means/conceito.md
    - Projeto: ./classes/k-means/main.md
  - Comparação de Modelos:
    - Métricas de Avaliação: ./classes/metricas/main.md
  - Random Forest:
    - Conceito: ./classes/random-forest/conceito.md
    - Projeto: ./classes/random-forest/main.md
  - Gradient Boosting:
    - Conceito: ./classes/gradient/conceito.md
    - Projeto: ./classes/gradient/main.md
  - Projeto: ./classes/projeto/main.md
  - Quiz:
    - Questões Básicas de Conceitos: ./classes/quiz/conceitos.md
    - Questões Estudos para a Prova 1: ./classes/quiz/prova1.md
